---

- name: Add postgres apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: Add postgres repo
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: pgdg

- name: Install postgres
  apt:
    name: "postgresql-{{ postgres_version }}"
    state: present
    update_cache: true
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: Install psycopg2
  apt:
    name: "python-psycopg2"
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: Start postgres
  service:
    name: postgresql
    state: started

- name: Create db
  postgresql_db:
    name: "{{ postgres_db_name }}"
    encoding: UTF8
    template: template0
  become_user: postgres
  become: true

- name: Create db user
  postgresql_user:
    db: "{{ postgres_db_name }}"
    name: "{{ postgres_db_user }}"
    password: "{{ postgres_db_password }}"
    priv: ALL
    state: present
  become_user: postgres
  become: true
