---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length: disable
platforms:
  - name: ansible-unifi
    image: ubuntu:${UBUNTU_IMAGE_TAG:-latest}
provisioner:
  name: ansible
  options:
    v: false
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
