---
- name: Prepare
  hosts: all
  become: true
  vars:
    apt_install_packages:
      - name: software-properties-common
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      register: result
      until: result is success
      retries: 5
      delay: 5
  roles:
    - calvinbui.ansible_apt
